trainset:
  fprimer: CCTACGGGNGGCWGCAG
  rprimer: GACTACHVGGGTATCTAATCC
  minlength: 350
  maxlength: 580

threads: 8

dada:
  trunclength:
    f: 290
    r: 220

  maxEE:
    f: 9
    r: 15

deblur:
  use: TRUE
  trimlength: 520

DAT:
  metaDcolumn: condition