trainset:
  fprimer: CCTACGGGNGGCWGCAG
  rprimer: GACTACHVGGGTATCTAATCC
  minlength: 350
  maxlength: 580

threads: 60

dada:
  trunclength:
    f: 290
    r: 270

  maxEE:
    f: 8
    r: 9


alphararefaction:
  maxdepth: 10000

core_met_phylo:
  samplingdepth: 25000

