#!/bin/bash

## this is main file of analysis
## it takes command line arguments to perfrome specific analysis pipline.

# opens piplines script file
eval "$(conda shell.bash hook)"
conda deactivate
conda activate GUAP

myfolder=~/GUAP
source ~/GUAP/bin/common/common_functions.sh
source ~/GUAP/bin/common/indexes.sh
current=$PWD
# usage message
__usage="
GUAP v1.0
Usage: $(basename $0) [OPTIONS]

GUAP <16s|DE|vizUI> -i <inputdir> -o <outputdir> [...] 
____________________________________________________________

16s:

usage: GUAP 16s -i [input] -o [output] -m [metadata] -c [classifier]

____________________________________________________________

DE:

Usage: GUAP DE -i [INPUT] -c [clinical] -S [sample] -C [control] -o [out-dir]

____________________________________________________________

vizUI:

GUAP vizUI

____________________________________________________________

This workflow is still under development thank you for testing 
for any bugs please contact: Abdelrhman @ abdelrhman.yahia@57357.org
"

# function to print usage message and exits 
usage() {
    echo -e "$__usage" 1>&2; exit 1
}

# assigns default value for miRNA analysis
THREADS=8
interactive=False
if [ "$#" -eq 0 ]
then
  usage
  exit 1
fi
eval $(parse_yaml ${myfolder}/config.yml)
if [ $1 == "16s" ];then
    python3 ~/GUAP/bin/16s/16s.py "${@:2}"
    if [[ ! -f ~/GUAP/bin/16s/temp.sh ]] ;then
    exit
    fi
    source ~/GUAP/bin/16s/temp.sh
    error_cheker $?
    rm ~/GUAP/bin/16s/temp.sh
    if [[ ! -f ${meta} ]] ;then
    echo -e "${BLU}${meta}${RED} IS NOT FOUND... ${NC}"
    exit
    fi
    if [ ${interactive} == "True" ];then
        take_args
    fi
    run_16s
elif [ $1 == "DE" ];then
    args="${@:2} --wd ${current}/"
    echo -e "${YEL}DE analysis started... ${NC}"
    Rscript ~/GUAP/bin/miRNA/GDEv1.2.R $args
elif [ $1 == "-h" ] || [ $1 == "--help" ] || [ $1 == "help" ];then
    usage
elif [ $1 == "vizUI" ];then
    Rscript -e 'library(methods); shiny::runApp("/home/gen/GUAP/bin/GUI/app.R", launch.browser = TRUE)'
else
  echo -e "${RED}ERROR: incorrect arguments${NC}"
  usage
  exit
fi