import os
import pandas as pd

configfile: "config.yaml"

include: "rules/miRNA_direct.smk"
include: "rules/miRNA_miRBase.smk"
include: "rules/QC_cutadapt.smk"

rule all:
    input:
        # expand("OUT/cutadapt/{sample}.fastq", sample=SAMPLES)
        # expand("OUT/rawQC/{sample}_fastqc.{extension}", sample=SAMPLES, extension=["zip","html"]),
        expand("OUT/miRNA_human/mapped_reads/{sample}_human.stats", sample=SAMPLES),
        expand("OUT/miRBase/mapped_reads/{sample}_miRBase.stats", sample=SAMPLES),
        expand("OUT/miRBase/counts/{sample}.counts", sample=SAMPLES),
        "OUT/miRNA_human/counts/final_human_counts.txt"

